# Generated by Django 3.1.7 on 2021-05-02 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('heading', models.CharField(max_length=100)),
                ('body', models.TextField(max_length=1000000000)),
                ('created', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='pics')),
                ('author', models.CharField(default='Deep', max_length=60)),
                ('category', models.CharField(max_length=60)),
                ('read_time', models.CharField(max_length=10)),
            ],
        ),
    ]
